### ISSUE TITLE
Type check test fails on `cast_call`

### ISSUE THREAD

**Issue by jnfoster** [verified-network-toolchain/petr4#333] opened 2022-03-11 15:06 UTC
Running `make test` on the `main` branch halts with this bug:
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        typecheck tests good            445   cast-call.p4.                                                                                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Testing file ../examples/checker_tests/good/cast-call.p4...
Unknown exception: ("illegal explicit cast"
  (old_type
    (Function
      ((type_params (T))
        (parameters
          (((annotations ()) (direction Directionless)
             (typ (TypeName (BareName ((M "") T))))
             (variable
               ((I (filename ../examples/checker_tests/good/cast-call.p4)
                  (line_start 21) (line_end ()) (col_start 16) (col_end 17))
                 x))
             (opt_value ()))))
        (kind Extern) (return (TypeName (BareName ((M "") T)))))))
  (new_type (Bit ((width 32)))))ASSERT good test
FAIL good test

   Expected: `true'
   Received: `false'

Raised at Alcotest_engine__Test.check in file "src/alcotest-engine/test.ml", line 196, characters 4-261
Called from Alcotest_engine__Core.Make.protect_test.(fun) in file "src/alcotest-engine/core.ml", line 180, characters 17-23
Called from Alcotest_engine__Monad.Identity.catch in file "src/alcotest-engine/monad.ml", line 24, characters 31-35
```
This looks like a regression...

**Comment by hackedy** [comment] 2022-03-15 16:01
Not a regression, but an old bug (#69). The test case is excluded from `make ci-test`, maybe we should just make that the `make test` target?

**Comment by hackedy** [comment] 2023-04-06 16:14
Closing as duplicate of #69

**Closed by hackedy** 2023-04-06 16:14 UTC
